                    <div class="modal-header">

                        <h3 class="modal-title custom-font"><font class="text-blue"><strong>Cab Request Id : </strong>  <?php echo $f_request_id; ?></font> </h3>

                    </div>

                    <div class="modal-body">

                        <p>

                            <?php if (!empty($modal_result) ) { ?>

                            <table border="0" > 

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Generated by</b>    :    </font><font class="text-slategray"><?php echo $modal_result->employee_id; ?></font></td><td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Request generated on</b>    :    </font><font class="text-slategray"><?php echo $modal_result->date_request; ?></font></td>  </tr>

                                <tr> <td style="padding : 5px;" width="350"><font class="text-darkgray"><b>State</b>    :    </font><font class="text-slategray">
                                       <?php echo $modal_result->state_name; ?>
                                       </font></td> </tr>
                                <tr><td style="padding : 5px;" width="270"><font class="text-darkgray"><b>City</b>    :    </font><font class="text-slategray"><?php echo $modal_result->city_name; ?></font></td></tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>from_loc</b>    :    </font><font class="text-slategray"><?php echo $modal_result->from_loc; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>to_loc</b>    :    </font><font class="text-slategray"><?php echo $modal_result->to_loc ; ?></font></td></tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Travel Date</b>    :    </font><font class="text-slategray"><?php echo $modal_result->journey_date; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Time</b>    :    </font><font class="text-slategray"><?php echo $modal_result->from_time; ?></font></td>  </tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Person Contact no.</b>    :    </font><font class="text-slategray"><?php echo $modal_result->person_mob_no; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Person Age</b>    :    </font><font class="text-slategray"><?php echo $modal_result->person_age; ?></font></td></tr>

                                 <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>frequent_flier_no</b>    :    </font><font class="text-slategray"><?php echo $modal_result->frequent_flier_no; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>funct_dept </b>    :    </font><font class="text-slategray"><?php echo $modal_result->funct_dept ; ?></font></td></tr>


                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Status</b>    :    </font><font class="text-success"><?php echo $modal_result->status_data; ?></font></td></tr>

                            </table> <?php  } ?>



                        </p>

                        

                    </div>

                    <div class="modal-footer">
                    <button class="btn btn-danger"  onclick="refresh_flt_data()" data-dismiss="modal">Close</button>
                    </div>

             

        