                    <div class="modal-header">

                        <h3 class="modal-title custom-font"><font class="text-blue"><strong>Hotel Request Id : </strong>  <?php echo $h_request_id; ?></font> </h3>

                    </div>

                    <div class="modal-body">

                        <p>

                            <?php if (!empty($modal_result) ) { ?>

                            <table border="0" > 

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Generated by</b>    :    </font><font class="text-slategray"><?php echo $modal_result->generated_by; ?></font></td><td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Request generated on</b>    :    </font><font class="text-slategray"><?php echo $modal_result->date_time_request; ?></font></td>  </tr>

                                <tr> <td style="padding : 5px;" width="350"><font class="text-darkgray"><b>State</b>    :    </font><font class="text-slategray">
                                       <?php echo $modal_result->state_name; ?>
                                       </font></td> </tr>
                                <tr><td style="padding : 5px;" width="270"><font class="text-darkgray"><b>City</b>    :    </font><font class="text-slategray"><?php echo $modal_result->city_id; ?></font></td></tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Checkin_date</b>    :    </font><font class="text-slategray"><?php echo $modal_result->checkin_date; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Checkout_date</b>    :    </font><font class="text-slategray"><?php echo $modal_result->checkout_date; ?></font></td></tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Checkin_time</b>    :    </font><font class="text-slategray"><?php echo $modal_result->checkin_time; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Checkout_time</b>    :    </font><font class="text-slategray"><?php echo $modal_result->checkout_time; ?></font></td>  </tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>No_of_rooms</b>    :    </font><font class="text-slategray"><?php echo $modal_result->no_of_rooms; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>No_of_persons</b>    :    </font><font class="text-slategray"><?php echo $modal_result->no_of_persons; ?></font></td></tr>

                                 <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>1st Preference</b>    :    </font><font class="text-slategray"><?php echo $modal_result->fst_preference; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>2nd Preference</b>    :    </font><font class="text-slategray"><?php echo $modal_result->scnd_preference; ?></font></td></tr>


                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Status</b>    :    </font><font class="text-success"><?php echo $modal_result->status_data; ?></font></td></tr>

                                <?php if(!empty($modal_result->guest_name)){ ?>
                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Booking for Guest</b>    :    </font><font class="text-success">YES</font></td><td style="padding : 5px;" width="270"><b>Guest Name</b>    :    <?php echo $modal_result->guest_name; ?></td></tr>
                                 <tr> <td style="padding : 5px;" width="270"><b>Guest Mob.</b>    :    <?php echo $modal_result->guest_mob; ?></td><td style="padding : 5px;" width="270"><b>Guest Email</b>    :   <?php echo $modal_result->guest_email; ?></td></tr>
                                 <?php } ?>

                                 <?php if(!empty($modal_result->spl_app) && $modal_result->spl_app==2){ ?>
                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Is any special request ?</b>    :    </font><font class="text-success">YES</font></td></tr>
                                 <tr> <td style="padding : 5px;" width="540"><b>Special details</b>    :    <?php echo $modal_result->spl_app_dtls; ?></td></tr>
                                 <?php } ?>

                            </table> <?php  } ?>



                        </p>

                        

                    </div>

                    <div class="modal-footer">
                    <button class="btn btn-danger"  onclick="refresh_htl_data()" data-dismiss="modal">Close</button>
                    </div>

             

        