 

                    <div class="modal-header">

                        <h3 class="modal-title custom-font"><font class="text-blue"><strong>Cab Request Id : </strong>  <?php echo $c_request_id; ?></font> </h3>

                    </div>

                    <div class="modal-body">

                        <p>

                            <?php if (!empty($modal_result) ) { ?>

                            <table border="0" > 

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Generated by</b>    :    </font><font class="text-slategray"><?php echo $modal_result->generated_by; ?></font></td><td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Request generated on</b>    :    </font><font class="text-slategray"><?php echo $modal_result->date_time_request; ?></font></td>  </tr>

                                <tr> <td style="padding : 5px;" width="350"><font class="text-darkgray"><b>State</b>    :    </font><font class="text-slategray">
                                       <?php echo $modal_result->state_name; ?>
                                       </font></td> </tr>
                                <tr><td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Source City</b>    :    </font><font class="text-slategray"><?php echo $modal_result->city_id; ?></font></td> <?php if(!empty($modal_result->outstation_city)) { ?> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Destination City</b>    :    </font><font class="text-slategray"><?php echo $modal_result->outstation_city; ?></font></td> <?php } ?></tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Date of Journey</b>    :    </font><font class="text-slategray"><?php echo $modal_result->pickup_date; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Time</b>    :    </font><font class="text-slategray"><?php echo $modal_result->pickup_time; ?></font></td></tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Pick Up Point</b>    :    </font><font class="text-slategray"><?php echo $modal_result->pickup_point; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Drop Point</b>    :    </font><font class="text-slategray"><?php echo $modal_result->drop_point; ?></font></td>  </tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Package</b>    :    </font><font class="text-slategray"><?php echo $modal_result->package_name; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Vehicle Type</b>    :    </font><font class="text-slategray"><?php echo $modal_result->cab_category_name; ?></font></td></tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Cab Name</b>    :    </font><font class="text-slategray"><?php echo $modal_result->cab_name; ?></font></td> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Service Type</b>    :    </font><font class="text-slategray"><?php echo $modal_result->cab_service_name; ?></font></td></tr>

                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Status</b>    :    </font><font class="text-success"><?php echo $modal_result->status_data; ?></font></td></tr>

                                <?php if(!empty($modal_result->traveler_name)){ ?>
                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Booking for Guest</b>    :    </font><font class="text-success">YES</font></td><td style="padding : 5px;" width="270"><b>Guest Name</b>    :    <?php echo $modal_result->traveler_name; ?></td></tr>
                                 <tr> <td style="padding : 5px;" width="270"><b>Guest Mob.</b>    :    <?php echo $modal_result->traveler_mob; ?></td><td style="padding : 5px;" width="270"><b>Guest Email</b>    :   <?php echo $modal_result->traveler_email; ?></td></tr>
                                 <?php } ?>

                                 <?php if(!empty($modal_result->spl_app) && $modal_result->spl_app==2){ ?>
                                <tr> <td style="padding : 5px;" width="270"><font class="text-darkgray"><b>Is any special request ?</b>    :    </font><font class="text-success">YES</font></td></tr>
                                 <tr> <td style="padding : 5px;" width="540"><b>Special details</b>    :    <?php echo $modal_result->spl_app_dtls; ?></td></tr>
                                 <?php } ?>

                            </table> <?php  } ?>



                        </p>

                        

                    </div>

                    <div class="modal-footer">
                    <button class="btn btn-danger"  onclick="refresh_cab_data()" data-dismiss="modal">Close</button>
                    </div>

             

        